huproject/huapp/urls.py
from django.urls import path
from . import views

app_name = 'huapp'

urlpatterns = [
    path('index', views.index, name='index'),  # /first
    path('', views.home, name='home'),
    path('checkme', views.checkme, name='checkme'),
    path('library', views.library, name='library'),
    path('calendar', views.calendar, name='calendar'),

    path('new_entry', views.new_entry, name='new_entry'),

    path('image_uploads', views.image_upload, name='image_uploads'),
    path('post/<int:id>', views.post, name='post'),

    path('category/<str:name>', views.category, name='category')


]

huproject/huproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('huapp.urls')),
    path('users/', include('users.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

huproject/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

huproject/huapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Entry(models.Model):

    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "ДумкаФорма"
        verbose_name_plural = "ДумкиФорма"

    def __str__(self):
        return f'{self.text[:50]}...'


class Foto(models.Model):

    image = models.ImageField(upload_to='media')
    class Meta:
        verbose_name = "Зображення"
        verbose_name_plural = "УсіЗображення"




class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name = "Назва")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class Teg(models.Model):
    name = models.TextField(max_length=10)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Хештег"
        verbose_name_plural = "Хештеги"



class Post(models.Model):
    title = models.CharField(max_length=30, verbose_name = "Заголовок посту")
    content = models.TextField(verbose_name = "Опис посту")
    published_date = models.DateTimeField(auto_created=True, verbose_name = "Дата та час посту")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name = "Категорія")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = "Автор")
    # (юзер не потрібен бо акаунт
    # буде ен доступний для багатьох юзерів приберу це потім
    poster = models.URLField(
        default="https://images.pexels.com/photos/147465/pexels-photo-147465.jpeg?auto=compress&cs=tinysrgb&w=600",
        verbose_name = "Постер")
    teg = models.ManyToManyField(Teg, blank=True, related_name='posts', verbose_name="Хештеги")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "ПостБложний"
        verbose_name_plural = "ПостиБложні"





class LibText(models.Model):
    title = models.CharField(max_length=30, verbose_name="Заголовок мого поля з текстом")
    content = models.TextField(verbose_name="Зміст")
    to_category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Мій текст належить до Категорії")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Мій постик"
        verbose_name_plural = "Мої постики"


class CheckForm(models.Model):
    date = models.DateTimeField(verbose_name="дата опитування")
    answer1 = models.BooleanField(verbose_name="мені сумно", default=False)
    answer2 = models.BooleanField(verbose_name="мені весело", default=False)
    answer3 = models.BooleanField(verbose_name="мені норм", default=False)

    class Meta:
        verbose_name = "Опитуваннячко"
        verbose_name_plural = "Опитування"

huproject/users/models.py
from django.db import models

# Create your models here.

huproject/huapp/forms.py
from django import forms

from .models import Entry, Foto


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', ]
        labels = {'text': 'Entry text'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class FotoForm(forms.ModelForm):
    class Meta:
        model = Foto
        fields = ['image']

huproject/huapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import EntryForm, FotoForm
from django.contrib.auth.decorators import login_required
from .models import Category, Post, LibText, Teg

from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse





def get_categories():
    all = Category.objects.all()
    count = all.count()

    return {
        "cat1":all[:count//2],
        "cat2":all[count//2:]
    }


@login_required()
def image_upload(request):

    if request.method == 'POST':
        form = FotoForm(request.POST, request.FILES)

        if form.is_valid():

            form.save()
            return redirect('huapp:home')
    else:
        form = FotoForm()
    return render(request, 'huapp/image_uploads.html', {'form': form})

def success(request):
    return HttpResponse('successfully uploaded')


def index(request):
    return render(request, 'huapp/index.html')


@login_required()
def home(request):

    # тимчасовий приклад
    lst = ['one', 'two', 'three']
    title = "Вітаю!"
    context = {
        "title":title,
        "list_data": lst,
    }


    return render(request, 'huapp/home.html', context=context)


@login_required()
def checkme(request):
    return render(request, 'huapp/checkme.html')


@login_required()
def library(request):
    post_blog_list = Post.objects.all().order_by("-published_date")
    # id_post_blog_list = Post.objects.get(pk=1) #просто перевірили фільтр
    my_posts_list = LibText.objects.all()
    # category_list = Category.objects.all()

    tegs = Teg.objects.all()

    context = {"post_blog_list": post_blog_list,
               "my_posts_list": my_posts_list,
               # "category_list": category_list,
               # "post": id_post_blog_list,
               "tegs": tegs}
    context.update(get_categories())

    return render(request, 'huapp/library.html', context=context)


def post(request, id=None):
    post = get_object_or_404(Post, pk=id)
    context={"post": post}
    context.update(get_categories())
    return  render(request, 'huapp/post.html', context=context)


@login_required()
def calendar(request):
    return render(request, 'huapp/calendar.html')


@login_required()
def new_entry(request):

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.save()
            return redirect('huapp:home')

    context = {'form': form}
    return render(
        request,
        'huapp/new_entry.html',
        context=context)




def category(request, name=None):
    c = get_object_or_404(Category, name=name)
    posts = Post.objects.filter(category=c)
    context = {'posts': posts}
    context.update(get_categories())
    return render(request, 'huapp/library.html', context=context)

huproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            redirect('huapp:home')

    context = {'form': form}
    return render(
        request,
        'registration/register.html',
        context
    )

huproject/templates/base.html
<!DOCTYPE html>
<html lang="en">


{% load static %}
{% include 'menu.html' %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

<!--     Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <!-- Custom styles for this template -->
<!--  <link href="{% static 'huapp/style.css'%}" rel="stylesheet">-->

  </head>

<body>


    <main role="main" class="container">

      {% block content %}

        {% endblock %}


    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

huproject/templates/huapp/calendar.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<h1>календарна таблиця3</h1>

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>
</head>
    <!-- Custom styles for this template -->
<link href="{% static 'huapp/for_cal.css'%}" rel="stylesheet">
<body>

<p style="background-color:tomato;">Тицни на день та передивись попередньо додані записи та фото з подальшою можливістю зберегти! </p>

<table style="width: 100%;">
<colgroup>
  <col span="2" style="background-color: #D6EEEE">
</colgroup>
<tr>
<th>MON</th>
<th>TUE</th>
<th>WED</th>
<th>THU</th>
<th>FRI</th>
<th>SAT</th>
<th>SUN</th>
</tr>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
</tr>
<tr>
<td>8</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
<td>13</td>
<td>14</td>
</tr>
<tr>
<td>15</td>
<td>16</td>
<td>17</td>
<td>18</td>
<td>19</td>
<td>20</td>
<td>21</td>
</tr>
<tr>
<td>22</td>
<td>23</td>
<td>24</td>
<td>25</td>
<td>26</td>
<td>27</td>
<td>28</td>
</tr>
</table>

<button type="button">Отримати статистику !</button>
</body>
</html>

{% endblock %}

huproject/templates/huapp/checkme.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<link href="{% static 'huapp/new_check.css'%}" rel="stylesheet">
<h1>Перевірити свій стан!</h1>
<p style="background-color:tomato;">Опитування</p>

<input type="checkbox"  name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox"  name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>
<input type="checkbox"  name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>
<input type="checkbox"  name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox"  name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>
<input type="checkbox"  name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>
<input type="checkbox"  name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox"  name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>
<input type="checkbox"  name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>
<input type="checkbox"  name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox"  name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>
<input type="checkbox"  name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>
<input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>
<input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>

<input type="checkbox"  name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox"  name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>
<input type="checkbox"  name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>
<input type="checkbox"  name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox"  name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>

<input type="checkbox"  name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>
<input type="checkbox"  name="vehicle1" value="Bike">
<label for="vehicle1"> гарний настрій</label><br>
<input type="checkbox"  name="vehicle2" value="Car">
<label for="vehicle2"> поганий настрій</label><br>
<input type="checkbox"  name="vehicle3" value="Boat">
<label for="vehicle3"> середній настрій</label><br>
<input type="checkbox"  name="vehicle1" value="Bike">

<button type="button">зберегти !</button>

{% endblock %}

huproject/templates/huapp/home.html
{% extends 'base.html' %}



{% block content %}
{% load static %}


<link href="{% static 'huapp/for_home.css'%}" rel="stylesheet">

<h1>{{ title }}</h1>

<a class="nav-link" href="{% url 'huapp:new_entry' %}">Залишити свої важливі думки тут !</a>
<hr>
<hr>
<h3>зараз {% now "d/m/y h:i:s" %}</h3>
<hr>
<hr>

{# коментар мовою DTL #}

<ul>
    {% for item in list_data %}
        <li>{{ item|title }}</li>
    {% endfor %}
</ul>


<a class="nav-link" href="{% url 'huapp:image_uploads' %}">Завантажити зображення тут !</a>

{% endblock %}

huproject/templates/huapp/image_uploads.html
{% extends 'base.html' %}

{% block content %}

        <p style="background-color:Magenta">ДОДАТИ ФОТО або картинку, яка відповідає настрою ! :</p>
<div class="container">
    <hr>
      <hr>
      <hr>
     <form action="{% url 'huapp:image_uploads' %}"  method="post"  enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form.as_p }}
<!--            <input type="file" name="smth" >-->
            <button type="submit"  style="background-color:MediumSeaGreen">Завантажити зображення</button>
        </form>
</div>

{% endblock %}

huproject/templates/huapp/index.html
{% extends 'base.html' %}

{% block title %}Home page{% endblock title %}

{% block content %}

<h1>тута буде реєстраційна вхід сторінка</h1>


{% endblock %}

huproject/templates/huapp/library.html
{% extends 'base.html' %}



{% block content %}


{% load static %}

<link href="{% static 'huapp/for_lib.css'%}" rel="stylesheet">
<h1>бібліотека</h1>


<p style="background-color:rgb(132, 144, 202);">Емоції (від фр. é mouvoir — «у русі», «хвилювання», «збудження») — це внутрішнє переживання або рух настрою, наприклад радість, страх, гнів, смуток, які можуть бути викликані ситуацією чи подією. Емоції також можуть виникати спонтанно. Емоції є суб'єктивними переживаннями і пов'язані з фізичними реакціями, виразом обличчя та поведінкою.</p>
<h2>Класифікація емоцій</h2>
<p style="background-color:rgb(181, 144, 202);">За ступенем збудження чи заспокоєння розрізняють:

Стенічні емоції — підштовхують до вчинків, висловів, збільшують напругу сил. Людині важко мовчати, не діяти активно (радість, впевненість, тріумф, страх, злість).
Астенічні емоції — характеризуються пасивністю, бездіяльністю (страждання, неспокій, страх).
За наявністю відтінків задоволення або незадоволення розрізняють:

Позитивні емоції — породжуються узгодженням обставин з нормами, що відповідають світогляду цієї особи (задоволення, радість, захват, замилування, самовдоволення, упевненість, задоволеність собою, повага, довіра, симпатія, ніжність, любов, вдячність, спокійна совість, полегшення, безпека, каяття, каяття совісті, й ін.).
Негативні емоції — породжуються відхиленням обставин від параметрів життєдіяльності конкретної людини як особистості (горе (скорбота), невдоволення, туга, сум, нудьга, розпач, засмучення, тривога, переляк, страх, жах, жалість, розчарування, образа, гнів, презирство, обурення, гордість, ворожість, заздрість, ненависть, злість, ревнощі, сумнів, розгубленість, зніяковілість, сором, відраза і т. д.)..</p>
<h2>Фундаментальні емоції</h2>
<p style="background-color:rgb(89, 144, 202);">
З часів Аристотеля налічують шість основних емоцій: радість, здивування, сум, гнів, страх і огиду[38].

Десять фундаментальних емоцій (за К. Ізардом) — це цікавість, радість, здивування, гнів, горе, відраза, зневага, страх, сором та вина.

Кожна фундаментальна емоція має властиві тільки для неї адаптивні функції з унікальними мотиваційними якостями, винятково важливими для кожного індивіду та для всього виду.

Емоції називаються фундаментальними, оскільки кожна з них має:

специфічні внутрішньо детерміновані нервові субстрати;
характерні мімічні або нервово-м'язові виразні комплекси;
відмінне суб'єктивне переживання або феноменологічну якість.
Жоден з цих компонентів не утворює емоцію самостійно. Цілісна емоція (або повний емоціональний процес) вимагає всіх цих трьох компонентів, хоч в одному з них — виражальному комплексі — і тривалість, і інтенсивність послаблюються соціалізацією.</p>


<div>
    <h4>Категорії!!</h4>
    <div class="row">
        <div class="col-lg-6">
            <ul class="list-unstyled">
                {% for cat in cat1 %}
                <li>
                    <a href="{% url 'huapp:category' name=cat.name %}">{{cat.name}}</a>
                {% endfor %}
                </li>
            </ul>
            </div>
            <div class="col-lg-6">
             <ul class="list-unstyled">
                {% for cat in cat2 %}
                <li>
                    <a href="{% url 'huapp:category' name=cat.name %}">{{cat.name}}</a>
                {% endfor %}
                </li>
            </ul>

        </div>
    </div>
</div>




<!--вибіркова фільтрація по id -->
    <h1 class="page-header">
        <a >{{post.title}}  </a>
    </h1>

    <p><a>автор: {{ post.user }}</a>
    </p>
    <p>дата поступ: {{ post.published_date }}</p>
    <hr>
    <img class="img-responsive" src="{{post.poster}}" alt="">
    <hr>
    <p> {{ post.content }} </p>
    <hr>




{% for post in post_blog_list %}
    <h1 class="page-header">
        <a >{{post.title}} </a>
    </h1>
    <p><a>автор: {{ post.user }}</a>
        {% for teg in tegs %}
    <p><a> {{ teg.name }}</a>
    {% endfor %}
    </p>
    <p>дата поступ: {{ post.published_date }}</p>
    <hr>
    <img class="img-responsive" src="{{post.poster}}" alt="">
    <hr>
    <p> {{ post.content }} </p>


        <a class="btn btn-primary" href="{% url 'huapp:post' id=post.id %}">читати більше

         </a>
<hr>
<hr>

{% endfor %}


{% for post in my_posts_list %}
    <h1 class="page-header">
        <a> {{post.title}} </a>
    </h1>

    <hr>

    <p> {{ post.content }} </p>
    <hr>
{% endfor %}


</div>
{% endblock content %}

huproject/templates/huapp/new_entry.html
{% extends 'base.html' %}

{% block title %}HOME PAGE{% endblock title %}

{% block content %}


    <p style="background-color:MediumSeaGreen">ДОДАТИ свої думки:</p>
    <form action="{% url 'huapp:new_entry' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>
{% endblock %}

huproject/templates/huapp/post.html
{% extends 'base.html' %}



{% block content %}


{% load static %}

<link href="{% static 'huapp/for_lib.css'%}" rel="stylesheet">

    <h1 class="page-header">
        <a >{{post.title}} </a>
    </h1>
    <p><a>автор: {{ post.user }}</a>

    </p>
    <p>дата поступ: {{ post.published_date }}</p>
    <hr>
    <img class="img-responsive" src="{{post.poster}}" alt="">
    <hr>
    <p> {{ post.content }} </p>
{% endblock content %}

huproject/templates/menu.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-left">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
              aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'huapp:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'huapp:calendar' %}">Calendar</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'huapp:library' %}">Library</a>
          </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'huapp:checkme' %}">Checkme</a>
          </li>
        </ul>
          <span class="navbar-text">
            {% if user.is_authenticated %}
              Hello, {{ user.username }},
              <form action="{% url 'users:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Logout</button>
              </form>
            {% else %}
              <a href="{% url 'users:login' %}">Log In</a>
              <a href="{% url 'users:register' %}">Register</a>
            {% endif %}

          </span>
      </div>
    </nav>